---
- name: Pull docker image of devops_calculator
  hosts: localhost
  tasks:
    - name: Pull devops_calculator devops image
      docker_image:
        name: richavarma/my_docker_repo
        source: pull
